/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Modelo({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Modelo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={nodes.mesh_0_1.material} />
        <mesh geometry={nodes.mesh_0_2.geometry} material={nodes.mesh_0_2.material} />
        <mesh geometry={nodes.mesh_0_3.geometry} material={nodes.mesh_0_3.material} />
        <mesh geometry={nodes.mesh_0_4.geometry} material={nodes.mesh_0_4.material} />
        <mesh geometry={nodes.mesh_0_5.geometry} material={nodes.mesh_0_5.material} />
        <mesh geometry={nodes.mesh_0_6.geometry} material={nodes.mesh_0_6.material} />
        <mesh geometry={nodes.mesh_0_7.geometry} material={nodes.mesh_0_7.material} />
        <mesh geometry={nodes.mesh_0_8.geometry} material={nodes.mesh_0_8.material} />
        <mesh geometry={nodes.mesh_0_9.geometry} material={nodes.mesh_0_9.material} />
        <mesh geometry={nodes.mesh_0_10.geometry} material={nodes.mesh_0_10.material} />
        <mesh geometry={nodes.mesh_0_11.geometry} material={nodes.mesh_0_11.material} />
        <mesh geometry={nodes.mesh_0_12.geometry} material={nodes.mesh_0_12.material} />
        <mesh geometry={nodes.mesh_0_13.geometry} material={nodes.mesh_0_13.material} />
        <mesh geometry={nodes.mesh_0_14.geometry} material={nodes.mesh_0_14.material} />
        <mesh geometry={nodes.mesh_0_15.geometry} material={nodes.mesh_0_15.material} />
        <mesh geometry={nodes.mesh_0_16.geometry} material={nodes.mesh_0_16.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Modelo.glb')

